# Configurações para ambiente de produção

market:
  timeframe: 1m
  min_volume: 200  # Maior exigência de volume

trading:
  initial_capital: 100000
  max_positions: 3
  stop_loss: 2.0  # Mais conservador
  max_daily_loss: -1500  # Mais restritivo